# Generated by Django 2.2.3 on 2019-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('book_gender', models.CharField(max_length=20)),
                ('book_id', models.CharField(max_length=20)),
                ('bcontent', models.CharField(max_length=20)),
            ],
        ),
    ]
